-- Fixture data for assistants (basketball)
INSERT INTO assistants (name, sport, role, strengths, bio, prompt_template, created_at, updated_at) VALUES
('Coach Maverick', 'Basketball', 'Guard', ARRAY['Ball Handling', 'Basketball IQ', 'Pick-and-Roll Execution'], 'A seasoned floor general who teaches guards how to read defenses, run plays, and lead the offense with precision.', 'Create a 1-week training plan to enhance {goal} for a basketball guard. Focus on ball handling and decision-making under pressure.', NOW(), NOW()),
('Coach Titan', 'Basketball', 'Center', ARRAY['Rim Protection', 'Post Defense', 'Shot Blocking'], 'A defensive anchor with a focus on timing, footwork, and paint dominance. Teaches how to protect the rim without fouling.', 'Design a training schedule to boost rim protection skills for a basketball center. Include shot-blocking drills and positioning strategies.', NOW(), NOW()),
('Coach Blaze', 'Basketball', 'Wing', ARRAY['Shooting', 'Off-Ball Movement', 'Shot Creation'], 'An offensive specialist who trains players to create space, move without the ball, and become lethal from the perimeter.', 'Build a custom training routine to improve shooting consistency and off-ball awareness for a basketball wing.', NOW(), NOW()),
('Coach Nova', 'Basketball', 'Forward', ARRAY['Transition Offense', 'Finishing', 'Athleticism'], 'Brings explosive energy and speed-focused drills to enhance fast breaks, driving lanes, and above-the-rim finishes.', 'Develop a 5-day plan for boosting transition scoring and finishing at the rim for an athletic forward.', NOW(), NOW()),
('Coach Ice', 'Basketball', 'Guard', ARRAY['Clutch Performance', 'Free Throws', 'End-of-Game Execution'], 'A calm and collected leader who thrives under pressure. Specializes in teaching composure, free throw routines, and end-of-game execution for guards.', 'Outline a training strategy to build composure and efficiency in clutch moments for a basketball guard.', NOW(), NOW()),
('Coach Atlas', 'Basketball', 'Center', ARRAY['Rebounding', 'Strength Training', 'Box Out Fundamentals'], 'A physicality-first coach who teaches players to control the glass with technique, strength, and hustle.', 'Craft a strength-focused training plan that emphasizes rebounding technique and box-out fundamentals.', NOW(), NOW()),
('Coach Vibe', 'Basketball', 'Wing', ARRAY['Team Chemistry', 'Communication', 'Court Awareness'], 'Believes that great players make their teammates better. Focuses on awareness, unselfish play, and leadership.', 'Generate a training routine that builds communication, team cohesion, and court awareness for a versatile wing.', NOW(), NOW()),
('Coach Spark', 'Basketball', 'Guard', ARRAY['Quickness', 'Agility', 'Full-Court Pressure'], 'A high-energy coach who thrives on intensity. Trains guards to press, harass ball handlers, and change pace effectively.', 'Prepare a high-intensity plan to improve quickness, agility, and pressure defense for a basketball guard.', NOW(), NOW()),
('Coach Prism', 'Basketball', 'Forward', ARRAY['Defensive Switching', 'Versatility', 'Tactical IQ'], 'A versatile forward who excels at defensive switching and tactical play. Coaches players to read the game, adapt on the fly, and contribute in multiple roles.', 'Design a week-long training block for a forward focused on defensive switching, versatility, and tactical IQ.', NOW(), NOW()),
('Coach Echo', 'Basketball', 'Any', ARRAY['Film Study', 'Self-Assessment', 'Growth Mindset'], 'A reflective coach focused on reviewing past performances to drive future improvement through self-awareness.', 'Generate a training program that includes film breakdown, reflection prompts, and self-assessment for any basketball role.', NOW(), NOW());

-- Create a sample coach first (this would normally be created through the auth flow)
INSERT INTO coaches (user_id, email, first_name, last_name, display_name, timezone, account_status, onboarding_completed, created_at, updated_at) VALUES
('550e8400-e29b-41d4-a716-446655440000', 'coach@example.com', 'Sample', 'Coach', 'Coach Sample', 'UTC', 'ACTIVE', true, NOW(), NOW());

-- Get the coach ID for the sample coach
-- Note: In a real scenario, this would be handled by the application logic
-- For seed data, we'll use a known UUID

-- Fixture data for athletes (using the sample coach's ID)
INSERT INTO athletes (coach_id, first_name, last_name, email, tags, notes, sport, birthday, gender, fitness_level, training_history, height, weight, created_at, updated_at, deleted_at) VALUES
((SELECT id FROM coaches WHERE email = 'coach@example.com'), 'Alice', 'Smith', 'alice.smith1@example.com', ARRAY['athlete','yoga'], 'Loves yoga. See https://placekitten.com/200/200', 'Yoga', '1990-01-01', 'FEMALE', 'INTERMEDIATE', '5 years of yoga', 165.0, 60.0, NOW(), NOW(), NULL),
((SELECT id FROM coaches WHERE email = 'coach@example.com'), 'Bob', 'Johnson', 'bob.johnson2@example.com', ARRAY['runner'], 'Marathon runner. https://placekitten.com/201/200', 'Running', '1985-05-12', 'MALE', 'ADVANCED', '10 marathons', 180.0, 75.0, NOW(), NOW(), NULL),
((SELECT id FROM coaches WHERE email = 'coach@example.com'), 'Carol', 'Williams', 'carol.williams3@example.com', ARRAY['swimmer'], 'Competitive swimmer.', 'Swimming', '1992-03-15', 'FEMALE', 'ADVANCED', 'Swims daily', 170.0, 62.0, NOW(), NOW(), NULL),
((SELECT id FROM coaches WHERE email = 'coach@example.com'), 'David', 'Brown', 'david.brown4@example.com', ARRAY['basketball'], 'Plays center.', 'Basketball', '1988-07-22', 'MALE', 'INTERMEDIATE', 'Plays in local league', 200.0, 95.0, NOW(), NOW(), NULL),
((SELECT id FROM coaches WHERE email = 'coach@example.com'), 'Eva', 'Jones', 'eva.jones5@example.com', ARRAY['triathlete'], 'Training for first triathlon.', 'Triathlon', '1995-11-30', 'FEMALE', 'BEGINNER', 'New to triathlon', 168.0, 58.0, NOW(), NOW(), NULL),
((SELECT id FROM coaches WHERE email = 'coach@example.com'), 'Frank', 'Garcia', 'frank.garcia6@example.com', ARRAY['soccer'], 'Midfielder.', 'Soccer', '1991-09-10', 'MALE', 'INTERMEDIATE', 'Plays weekly', 175.0, 70.0, NOW(), NOW(), NULL),
((SELECT id FROM coaches WHERE email = 'coach@example.com'), 'Grace', 'Martinez', 'grace.martinez7@example.com', ARRAY['tennis'], 'Loves doubles.', 'Tennis', '1987-04-18', 'FEMALE', 'ADVANCED', 'Competes in tournaments', 160.0, 55.0, NOW(), NOW(), NULL),
((SELECT id FROM coaches WHERE email = 'coach@example.com'), 'Henry', 'Rodriguez', 'henry.rodriguez8@example.com', ARRAY['cycling'], 'Road cyclist.', 'Cycling', '1983-12-05', 'MALE', 'ADVANCED', 'Rides 200km/week', 178.0, 72.0, NOW(), NOW(), NULL),
((SELECT id FROM coaches WHERE email = 'coach@example.com'), 'Ivy', 'Lee', 'ivy.lee9@example.com', ARRAY['climbing'], 'Bouldering enthusiast.', 'Climbing', '1996-06-21', 'FEMALE', 'INTERMEDIATE', 'Climbs 3x/week', 162.0, 54.0, NOW(), NOW(), NULL),
((SELECT id FROM coaches WHERE email = 'coach@example.com'), 'Jack', 'Walker', 'jack.walker10@example.com', ARRAY['crossfit'], 'Crossfit regular.', 'CrossFit', '1993-08-14', 'MALE', 'INTERMEDIATE', 'Crossfit 4x/week', 182.0, 80.0, NOW(), NOW(), NULL),
((SELECT id FROM coaches WHERE email = 'coach@example.com'), 'Kara', 'Hall', 'kara.hall11@example.com', ARRAY['pilates'], 'Pilates instructor.', 'Pilates', '1989-02-27', 'FEMALE', 'ADVANCED', 'Teaches pilates', 167.0, 57.0, NOW(), NOW(), NULL),
((SELECT id FROM coaches WHERE email = 'coach@example.com'), 'Liam', 'Allen', 'liam.allen12@example.com', ARRAY['swimming'], 'Open water swimmer.', 'Swimming', '1994-10-09', 'MALE', 'INTERMEDIATE', 'Swims lakes', 176.0, 68.0, NOW(), NOW(), NULL),
((SELECT id FROM coaches WHERE email = 'coach@example.com'), 'Mia', 'Young', 'mia.young13@example.com', ARRAY['yoga'], 'Yoga teacher.', 'Yoga', '1990-05-19', 'FEMALE', 'ADVANCED', 'Teaches vinyasa', 164.0, 56.0, NOW(), NOW(), NULL),
((SELECT id FROM coaches WHERE email = 'coach@example.com'), 'Noah', 'King', 'noah.king14@example.com', ARRAY['basketball'], 'Point guard.', 'Basketball', '1986-03-23', 'MALE', 'ADVANCED', 'Plays semi-pro', 188.0, 85.0, NOW(), NOW(), NULL),
((SELECT id FROM coaches WHERE email = 'coach@example.com'), 'Olivia', 'Wright', 'olivia.wright15@example.com', ARRAY['running'], 'Trail runner.', 'Running', '1997-07-30', 'FEMALE', 'INTERMEDIATE', 'Runs trails', 169.0, 59.0, NOW(), NOW(), NULL),
((SELECT id FROM coaches WHERE email = 'coach@example.com'), 'Paul', 'Lopez', 'paul.lopez16@example.com', ARRAY['cycling'], 'Mountain biker.', 'Cycling', '1984-11-11', 'MALE', 'INTERMEDIATE', 'Rides weekends', 181.0, 77.0, NOW(), NOW(), NULL),
((SELECT id FROM coaches WHERE email = 'coach@example.com'), 'Quinn', 'Hill', 'quinn.hill17@example.com', ARRAY['rowing'], 'Rowing club.', 'Rowing', '1992-01-05', 'NON_BINARY', 'BEGINNER', 'New to rowing', 172.0, 65.0, NOW(), NOW(), NULL),
((SELECT id FROM coaches WHERE email = 'coach@example.com'), 'Ruby', 'Scott', 'ruby.scott18@example.com', ARRAY['dance'], 'Ballet dancer.', 'Dance', '1995-09-17', 'FEMALE', 'ADVANCED', 'Performs ballet', 158.0, 50.0, NOW(), NOW(), NULL),
((SELECT id FROM coaches WHERE email = 'coach@example.com'), 'Sam', 'Green', 'sam.green19@example.com', ARRAY['football'], 'Quarterback.', 'Football', '1989-06-02', 'MALE', 'ADVANCED', 'Plays in league', 190.0, 90.0, NOW(), NOW(), NULL),
((SELECT id FROM coaches WHERE email = 'coach@example.com'), 'Tina', 'Baker', 'tina.baker20@example.com', ARRAY['yoga','running'], 'Yoga and running.', 'Yoga', '1993-12-25', 'FEMALE', 'INTERMEDIATE', 'Mixes yoga and running', 166.0, 58.0, NOW(), NOW(), NULL);
