import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter, Source_Sans_3, Epilogue } from "next/font/google";
import "@/app/globals.css";
import { SidebarInset } from "@/components/ui/sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import Footer from "@/components/footer";
import Header from "@/components/header";
import { AppSidebar } from "@/components/ui/app-sidebar";
import { UrqlProvider } from "@/components/ui/urql-provider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

// Define the new Google Fonts
const inter = Inter({
	variable: '--font-inter',
	subsets: ['latin'],
	display: 'swap',
});

const sourceSansPro = Source_Sans_3({
	variable: '--font-source-sans-pro',
	subsets: ['latin'],
	display: 'swap',
	weight: ['400', '600'], // Specify the weights you need
});

const epilogue = Epilogue({
	variable: '--font-epilogue',
	subsets: ['latin'],
	display: 'swap',
	weight: ['400', '600'], // Specify the weights you need
});

export const metadata: Metadata = {
	title: "congenial-carnival",
	description: "Generated by congenial-carnival",
};

export default function RootLayout({
	children,
}: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body
				className={`${inter.variable} ${sourceSansPro.variable} ${epilogue.variable} antialiased`}
			>
				<UrqlProvider>
					<SidebarProvider>
						<AppSidebar />
						<SidebarInset>
							{/* <Header /> */}
							<main className="flex-col justify-start align-top flex flex-1 p-4 gap-2">
								{children}
							</main>
						</SidebarInset>
					</SidebarProvider>
				</UrqlProvider>
			</body>
		</html>
	);
}
