import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { SidebarInset } from "@/components/ui/sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import Footer from "@/components/footer";
import Header from "@/components/header";
import { AppSidebar } from "@/components/ui/app-sidebar";
import { UrqlProvider } from "@/components/ui/urql-provider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "congenial-carnival",
	description: "Generated by congenial-carnival",
};

export default function RootLayout({
	children,
}: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<UrqlProvider>
					<SidebarProvider>
						<AppSidebar />
						<SidebarInset>
							<Header />
							<main className="flex-col justify-start align-top flex flex-1 p-4 gap-2">
								{children}
							</main>
						</SidebarInset>
					</SidebarProvider>
				</UrqlProvider>
			</body>
		</html>
	);
}
