import type { Metadata } from "next";

import { Epilogue, Inter, Source_Sans_3 } from "next/font/google";
import "@/app/globals.css";
import Footer from "@/components/footer";
import Header from "@/components/header";
import { AppSidebar } from "@/components/ui/app-sidebar";
import { SidebarInset } from "@/components/ui/sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { UrqlProvider } from "@/components/ui/urql-provider";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
	display: "swap",
});

const sourceSansPro = Source_Sans_3({
	variable: "--font-source-sans-pro",
	subsets: ["latin"],
	display: "swap",
	weight: ["400", "600"], // Specify the weights you need
});

export const metadata: Metadata = {
	title: "congenial-carnival",
	description: "Generated by congenial-carnival",
};

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en">
			<body
				className={`antialiased ${inter.className} ${sourceSansPro.className}`}
			>
				<UrqlProvider>
					<SidebarProvider>
						<AppSidebar />
						<SidebarInset>
							{/* <Header /> */}
							<main className="bg-background text-foreground flex-col align-top flex flex-1 gap-2">
								{children}
							</main>
						</SidebarInset>
					</SidebarProvider>
				</UrqlProvider>
			</body>
		</html>
	);
}
