-- Join table: goal_session_logs (many-to-many)
-- Goals and session logs can be linked to track progress
-- A session can work on multiple goals, and a goal can be addressed across multiple sessions
CREATE TABLE goal_session_logs (
    goal_id UUID NOT NULL REFERENCES goals(id) ON DELETE CASCADE,
    session_log_id UUID NOT NULL REFERENCES session_logs(id) ON DELETE CASCADE,
    PRIMARY KEY (goal_id, session_log_id)
);

-- Join table: training_plan_assistants (many-to-many)
-- Training plans can be generated by multiple assistants or reference multiple assistant templates
CREATE TABLE training_plan_assistants (
    training_plan_id UUID NOT NULL REFERENCES training_plans(id) ON DELETE CASCADE,
    assistant_id UUID NOT NULL REFERENCES assistants(id) ON DELETE CASCADE,
    PRIMARY KEY (training_plan_id, assistant_id)
);

-- Join table: training_plan_goals (many-to-many)
-- Training plans can address multiple goals, and goals can be part of multiple training plans
-- This supports the GraphQL schema requirements for goalIds in CreateTrainingPlanInput
CREATE TABLE training_plan_goals (
    training_plan_id UUID NOT NULL REFERENCES training_plans(id) ON DELETE CASCADE,
    goal_id UUID NOT NULL REFERENCES goals(id) ON DELETE CASCADE,
    PRIMARY KEY (training_plan_id, goal_id)
);

